universe = container
container_image = /cvmfs/singularity.opensciencegrid.org/htc/pytorch:2.3.1-cuda11.8

log = job_$(tag)_$(Cluster)_$(Process).log
error = job_$(tag)_$(Cluster)_$(Process).err
output = job_$(tag)_$(Cluster)_$(Process).out

# bash script calling your executable along with path variables and appropriate environment setup
executable = run_generate_like.sh
arguments = denoiser_$(tag).pth $(config) $(tag)

# REPLACE with "Long" if job is predicted to take over 40 hrs
+JobDurationCategory = "Medium"

#----------------RESOURCE REQUESTS-------------------#

gpus_minimum_capability = 7.5
request_gpus = 1
request_cpus = 1

#change as appropriate
request_memory = 2GB
request_disk = 4GB

#--------------FILE TRANSFER HANDLING-----------------#

# REPLACE with the executable in your submit.sh script and any input files 
transfer_input_files = ../../src, generate_like.py, ../../config, test_sizes_large.csv, ../training/denoiser_$(tag).pth

# REPLACE with output files
transfer_output_files = $(tag)_like.hdf5
should_transfer_files = YES

# REPLACE with however many jobs you are queuing 
queue config,tag from generate_experiments.txt
